from dotenv import load_dotenv
import os

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

META_VERIFY_TOKEN = os.getenv("META_VERIFY_TOKEN")
META_INSTAGRAM_ACCESS_TOKEN = os.getenv("META_INSTAGRAM_ACCESS_TOKEN")
META_GRAPH_API_VERSION = os.getenv("META_GRAPH_API_VERSION", "v26.0")
META_INSTAGRAM_ACCOUNT_ID = os.getenv("META_INSTAGRAM_ACCOUNT_ID")